
# HTTP Listener Configuration

http.host=0.0.0.0
http.port=8081
http.path=/upload


# Azure Storage Configuration

azure.accountName=integrationstore1
azure.accountKey=DefaultEndpointsProtocol=https;AccountName=integrationstore1;AccountKey=DqHXvomd4UfoggQosW9koLT9XrqvCLjvCCMoi11EcTJxoM4SkHcXFfomfbG1ANNLAHUxcFlgZnAq+AStYYLaFA==;EndpointSuffix=core.windows.net