salesforce.consumerKey=3MVG9.Houp75EVdbmZeSimL0ZL51HZ9i9GPlY8UCAltgsy1D3ekbH86u_NfDo326kv2EM10EKjb6oPoEfkbeQ
salesforce.consumerSecret=4A48887EC3A500C52A0B3C106C80EB5D7529C2D7B0A0C7B1501FD7D448431E41
salesforce.username=venkata.bharath@nexturn.com.sfpartner
salesforce.password=Ramalakshumma@1